development:
  adapter: sqlite3
  database: db/jikoryu-twitter_development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/jikoryu-twitter_test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: jikoryu-twitter_production
  username: jikoryu-twitter
  password: <%= ENV['JIKORYU-TWITTER_DATABASE_PASSWORD'] %>
